version: "3.9"

services:
    rest_backend:
        build:
            context: .
            dockerfile: ./django.Dockerfile
        volumes:
            - .:/src/app
        working_dir: /src/app
        restart: unless-stopped
        command: sh -c "
            python manage.py migrate --noinput -v 0
            && python manage.py collectstatic --noinput --force-color -v 0
            && gunicorn --workers 5 --bind 0.0.0.0:8088 restaurantWeb.wsgi:application"
        ports:
            - "8083:8088"


