# Generated by Django 2.2.10 on 2020-03-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundImg', models.ImageField(upload_to='')),
                ('restaurantEngName', models.CharField(max_length=100)),
                ('restaurantChName', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
