# Generated by Django 2.2.10 on 2020-03-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='logoImg',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
